logo: # add logo name
title: Contadores de Estrellas - Proyecto de Ciencia Ciudadana para registrar las lluvias de estrellas
description: Un proyecto para que entre todos ayudemos a contar meteoros en las lluvias de estrellas.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: contadoresdeestrellas-family.png # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: logo-contadores.png # your photo
author-name: Equipo de trabajo # your name
about-author: Universidad Politécnica de Madrid + Instituto Astrofísico de Canarias # about author
email: proyectocontadoresdeestrellas@gmail.com # your email
website: http://www.contadoresdeestrellas.ciclope.info # you website

# Social link
twitter_url:   http://twitter.com/starcounters
instagram_url: https://www.instagram.com/contadoresdeestrellas/
facebook_url:  http://www.facebook.com/contadoresdeestrellas/

# Disqus
#discus_identifier: mr-brown # add your discus identifier

# Newsletter
#mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-122307630-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
